const mainApi = [
    {
        id: 1,
        image: "https://media.blueapron.com/recipes/2/c_main_dish_images/20140808-1607-30-3725/Main_20Dish_20Image.jpg?quality=80&width=850",
        category: "Beef",
        title: "Seared Hanger Steak",
        subTitle: "with Rosemary Fingerling Potatoes & Green Bean Salad",
        description: "Prized for its flavor, hanger steak is the choice cut of beef for those in the know. It has even earned the nickname 'butcher's steak' because butchers would often reserve it for themselves rather than offering it for sale. In this dish, we highlight the hanger steak's incredible flavor by serving it alongside jewel-like potatoes and a crisp green bean salad.",
        price: 359,
    },
    {
        id: 2,
        image: "https://media.blueapron.com/recipes/5/c_main_dish_images/20140808-1609-48-5109/MainDishImage.jpg?quality=80&width=850",
        category: "Beef",
        title: "Fresh Fettucelle Bolognese",
        subTitle: "with Baby Heirloom Carrots",
        description: "This comforting meal pays homage to the succulent pasta dishes of Bologna in northern Italy. The Bolognese meat sauce slowly simmers with Italian tomatoes and fresh heirloom carrots for an extra touch of sweetness. Just before serving, the dish is topped with aromatic basil, the quintessential finishing touch for any Italian masterpiece.",
        price: 289,
    },
    {
        id: 3,
        image: "https://media.blueapron.com/recipes/9/c_main_dish_images/20140808-1611-72-7880/GingerBeefStir_20Fry_BlueApron.jpg?quality=80&width=850",
        category: "Beef",
        title: "Ginger Beef Stir-Fry",
        subTitle: "with Tatsoi & Jasmine Rice",
        description: "Hoisin sauce is a key flavor component in sauces and glazes in many Asian-inspired dishes. Made from soybean paste, garlic, chilis, and various spices, this all-in-one ingredient is salty, sweet, and spiced at the same time. In this super-fast recipe, we mix half of the hoisin into the stir-fry and spoon the rest over the finished product for an elegant finish.",
        price: 399,
    },
    {
        id: 4,
        image: "https://media.blueapron.com/recipes/15/c_main_dish_images/20140808-1617-108-2979/MAINdishImage.jpg?quality=80&width=850",
        category: "Beef",
        title: "Stuffed Peppers",
        subTitle: "with Beef & Millet",
        description: "From the traditional “pimientos rellenos” of Spain to the stuffed “punjena paprika” of Croatia, stuffed peppers are an international delicacy that can be found in almost every cuisine across the globe. In one of our favorite variations, we use naturally raised ground beef and millet, an ancient whole grain cultivated for over 10,000 years. It’s believed that at one point, millet was even more popular than rice.",
        price: 499,
    },
    {
        id: 5,
        image: "https://media.blueapron.com/recipes/23/square_newsletter_images/20141218-2247-1414-6738/23.jpg?quality=80&width=850",
        category: "Beef",
        title: "Lamb Kofte Kebabs",
        subTitle: "with Sautéed Chickpeas & Cucumber Yogurt Sauce",
        description: "“Kofte” is a popular Middle Eastern dish whose name comes from the Turkish word for “ball.” This preparation is a variation on meatballs, using fresh herbs and traditional cooking methods. Dill and mint mixed into the meat add deep, complex flavor. Cooking the meat on skewers makes them easy to handle and fun to eat!",
        price: 159,
    },
    {
        id: 6,
        image: "https://media.blueapron.com/recipes/26/c_main_dish_images/20140808-1629-174-2240/BeefPadSeeEw_BlueApron.jpg?quality=80&width=850",
        category: "Beef",
        title: "Beef Pad See Ew",
        subTitle: "with Birdseye Chilis",
        description: "Pad See Ew (literally: “stir-fried soy sauce”) is a popular Thai and Lao noodle dish. It typically uses Chinese broccoli, a dark leafy green vegetable that has a stronger and slightly more bitter flavor than the common broccoli. Combined with slightly sweet mirin and spicy birdseye chilis, this quick and flavorful dish is a winner.",
        price: 299,
    },
    {
        id: 7,
        image: "https://media.blueapron.com/recipes/6/square_newsletter_images/20150528-1528-805-0810/MainDishImage3-SQ.jpg?quality=80&width=850",
        category: "Fish",
        title: "Seared Salmon & Preserved Lemon",
        subTitle: "with Red Quinoa & Pea Shoots",
        description: "Many North African cuisines use a special ingredient to bring unique flavor to dishes: preserved lemon. It’s created by marinating lemon in a briny mixture with sugar, which mellows the bitterness of the pith and accents the lemon’s natural flavor. In this recipe, you’ll make a quick version of the classic ingredient and serve it with spring vegetables and crispy-skinned salmon for a wholesome meal with bright, incredible flavor.",
        price: 159,
    },
    {
        id: 8,
        image: "https://media.blueapron.com/recipes/8/c_main_dish_images/20140808-1611-66-7914/MainDishForWebsite.jpg?quality=80&width=850",
        category: "Fish",
        title: "Sweet Miso Cod",
        subTitle: "with Snap Peas, Farro & Lime Beurre Blanc",
        description: "This dish combines the sweet, earthy essence of miso with the citrus bite of lime. The roasted cod is accompanied by crisp sugar snap peas and farro, an Italian whole grain. Farro’s nutty, chewy texture is versatile enough to pair with almost any other flavors. Not only is this recipe super fast, but it also explodes with a unique combination of flavors and textures.",
        price: 699,
    },
    {
        id: 9,
        image: "https://media.blueapron.com/recipes/14/c_main_dish_images/20140808-1616-102-6796/Seared_20Trout_20Peach_20Arugula-9853.jpg?quality=80&width=850",
        category: "Fish",
        title: "Seared Trout",
        subTitle: "with Peach and Arugula Salad",
        description: "In this recipe, we combined the two complementary flavors of peach and tarragon, with the earthiness of potatoes and arugula. To achieve a nice brown color and crispy skin on your trout, make sure the pan is good and hot before adding the fish. We hope you’ll find this recipe to be a smash hit and a fun way to eat tasty fish.",
        price: 1200,
    },
    {
        id: 10,
        image: "https://media.blueapron.com/recipes/17/c_main_dish_images/20140808-1618-120-9907/FishTacos_BlueApron.jpg?quality=80&width=850",
        category: "Fish",
        title: "Chili-Dusted Fish Tacos",
        subTitle: "with Pickled Red Cabbage, Mango & Avocado",
        description: "This Mexican-inspired meal is a symphony of bright flavors and contrasting textures. The fresh cilantro and lime bring out the creaminess of the avocado, while the pickled cabbage and the spicy radish add snap and crunch. All of these sensations complement the flaky and tender tilapia fish. The final product—a colorful dish fit for a fiesta that we hope you’ll enjoy.",
        price: 459,
    },
    {
        id: 11,
        image: "https://media.blueapron.com/recipes/20/c_main_dish_images/20140808-1622-138-3158/CrispySkate_Final_1_original.jpg?quality=80&width=850",
        category: "Fish",
        title: "Skate Wing",
        subTitle: "with Crispy Lardons and Frisée",
        description: "If you have never seen a skate wing before it has been filleted, it might not be clear what it is you're eating. Skate is a type of fish that looks like a cross between a shark and ray. It is cartilaginous, which means that, like sharks, skates do not have bones but instead are held together by a substance softer and more flexible than bone. Skate fish have wide flippers that look like the wings of birds. The wing is the part of the fish that is typically eaten, hence the name.",
        price: 499,
    },
    {
        id: 12,
        image: "https://media.blueapron.com/recipes/22/c_main_dish_images/20140808-1626-150-2113/haddock_3x2.jpg?quality=80&width=850",
        category: "Fish",
        title: "White Fish 'En Papillote'",
        subTitle: "with Freekeh",
        description: "En Papillote is a French cooking method that literally translates to cook “in paper.” In this versatile technique, the food is baked in a folded packet, which holds in moisture and allows the flavors to meld while the ingredients steam and cook. This fish en papillote is served with freekeh, an ancient green grain from Egypt that derives its name from the Arabic word for the roasting process it undergoes.",
        price: 699,
    },
    {
        id: 13,
        image: "https://media.blueapron.com/recipes/5/c_main_dish_images/20140808-1609-48-5109/MainDishImage.jpg?quality=80&width=850",
        category: "Lamb",
        title: "Fresh Fettucelle Bolognese",
        subTitle: "with Baby Heirloom Carrots",
        description: "This comforting meal pays homage to the succulent pasta dishes of Bologna in northern Italy. The Bolognese meat sauce slowly simmers with Italian tomatoes and fresh heirloom carrots for an extra touch of sweetness. Just before serving, the dish is topped with aromatic basil, the quintessential finishing touch for any Italian masterpiece.",
        price: 199,
    },
    {
        id: 14,
        image: "https://media.blueapron.com/recipes/18/c_main_dish_images/20140808-1619-126-7151/LambSausage_Final_2_original.jpg?quality=80&width=850",
        category: "Lamb",
        title: "Lamb Sausage",
        subTitle: "with Late Summer Moroccan Couscous",
        description: "As the warm summer months come to an end and the nights begin to cool, a hearty dinner can be just what the doctor ordered. Fluffy couscous acts as the perfect bed for rich lamb sausages. It will soak up the savory juices and mingle with the fragrant end-of-summer herbs and vegetables. Add a final touch of citrus to conjure the flavors of a true mediterranean feast.",
        price: 799,
    },
    {
        id: 15,
        image: "https://media.blueapron.com/recipes/23/square_newsletter_images/20141218-2247-1414-6738/23.jpg?quality=80&width=850",
        category: "Lamb",
        title: "Lamb Kofte Kebabs",
        subTitle: "with Sautéed Chickpeas & Cucumber Yogurt Sauce",
        description: "“Kofte” is a popular Middle Eastern dish whose name comes from the Turkish word for “ball.” This preparation is a variation on meatballs, using fresh herbs and traditional cooking methods. Dill and mint mixed into the meat add deep, complex flavor. Cooking the meat on skewers makes them easy to handle and fun to eat!",
        price: 759,
    },
    {
        id: 16,
        image: "https://media.blueapron.com/recipes/65/c_main_dish_images/20140808-1718-198-5535/ShepherdsPie_Final_3_original.jpg?quality=80&width=850",
        category: "Lamb",
        title: "Shepherd’s Pie",
        subTitle: "with Baby Carrots and Leeks",
        description: "Recipes for shepherd’s pie, sometimes called “cottage pie,” date back to the late 1700s. Around this time, the potato became a popular food item in European countries and mashed potatoes formed the crust for this dish. Historically, lamb or mutton was used as the filling, but beef and other meats have become more popular in the last century.",
        price: 379,
    },
    {
        id: 17,
        image: "https://media.blueapron.com/recipes/181/c_main_dish_images/20140808-1958-18-2819/FINAL_original.jpg?quality=80&width=850",
        category: "Lamb",
        title: "Moussaka",
        subTitle: "with Lemony Parsley Salad",
        description: "Greek comfort food at its finest, this layered, baked casserole of meat, eggplant, and béchamel sauce was popularized by chef Nikolas Tselementes in the 1920s. Chef Tselementes studied cooking in Austria and used French and Western European influences (like béchamel) to modernize Greek cuisine to what we know it is today. In Greek, the word “Tselementes” is used as a synonym for cookbook. In the U.S. it’s hard to find a Greek restaurant that doesn’t have this fabulous dish on the menu.",
        price: 399,
    },
    {
        id: 18,
        image: "https://media.blueapron.com/recipes/255/c_main_dish_images/20140808-2016-138-7011/IMG_6359.jpg?quality=80&width=850",
        category: "Lamb",
        title: "Lamb & Beef Rice Noodles",
        subTitle: "with Mint, Lime & Ponzu",
        description: "This dish is inspired by the cuisines of Southeast Asia where the focus is on the balance of sour, salty, sweet, and bitter flavors. Here, sour comes from both the lime juice and the ponzu, a Japanese citrus sauce. Soy sauce adds saltiness and coconut palm sugar adds sweetness to help achieve that balance. Regular salt and pepper are still key for rounding out flavors, so don’t forget to season and taste as you go.",
        price: 299,
    },
    {
        id: 19,
        image: "https://media.blueapron.com/recipes/11/c_main_dish_images/20140808-1613-84-3678/MainDishImage.jpg?quality=80&width=850",
        category: "Pork",
        title: "Pork Chops with Salad",
        subTitle: "with Smashed Sweet Potato, Roasted Broccoli & Herbs",
        description: "As summer winds down, farmers start to harvest beautiful broccoli and a wide array of amazing potatoes. In this dish, we feature classic, juicy, center-cut pork chops with roasted broccoli and smashed sweet potato. Maple sugar, the reduced solid of maple syrup, not only helps us look forward to fall, but also lends a touch of sweetness to this dish.",
        price: 199,
    },
    {
        id: 20,
        image: "https://media.blueapron.com/recipes/21/c_main_dish_images/20140808-1624-144-3175/BakedOrzo_Final_2_original.jpg?quality=80&width=850",
        category: "Pork",
        title: "Baked Orzo Rice",
        subTitle: "with Chorizo and Mozzarella",
        description: "Orzo is the Italian word for barley, but in this case refers to the noodle's appearance. This pasta is made from semolina flour, which is more durable and therefore helps to maintain orzo's signature shape while cooking. Orzo is very popular in Mediterranean cooking and absorbs flavors beautifully. The orzo in this dish will meld the spice of the dried chorizo with the earthy vegetables and melted cheese.",
        price: 279,
    },
    {
        id: 21,
        image: "https://media.blueapron.com/recipes/31/square_newsletter_images/20141218-2124-2-0386/Gnocchi-Savoy-Cabbage-Sausage-SQ.jpg?quality=80&width=850",
        category: "Pork",
        title: "Gnocchi Salad",
        subTitle: "with Sausage and Savoy Cabbage",
        description: "Gnocchi is a special type of pasta (typically made from potato, flour and egg) that dates back to 14th Century Italy. The small ridges on the gnocchi are great for picking up the slightly spicy sauce in this dish, delivering more flavor in every bite. You’ll also be using savoy cabbage, a delicate, earthy variety with crinkly leaves and a delicious crunch. As always with fresh pasta, store it in the refrigerator until just before you’re ready to cook.",
        price: 499,
    },
    {
        id: 22,
        image: "https://media.blueapron.com/recipes/36/square_newsletter_images/20141218-2306-310-5886/36.jpg?quality=80&width=850",
        category: "Pork",
        title: "Center-Cut Pork Chops",
        subTitle: "with Caramelized Onions & Blue Cheese Grits",
        description: "Grits are a staple food in the American South. (In fact, grits are the official prepared state food of Georgia.) This Southern specialty is made from stone ground hominy and simmered until tender. We’re mixing in a little tangy blue cheese to add a smooth, creamy texture and a flavorful kick to this classic. We reckon you’ll love it.",
        price: 369,
    },
    {
        id: 23,
        image: "https://media.blueapron.com/recipes/90/c_main_dish_images/20140808-1738-144-0830/FINALforCArd.jpg?quality=80&width=850",
        category: "Pork",
        title: "Center-Cut Pork Chops with Pan Sauce",
        subTitle: "& Apple-Kohlrabi Slaw",
        description: "Kohlrabi, or “German turnip,” is a green vegetable related to broccoli and cabbage. The word “kohlrabi” is derived from the Austrian word “kohlrübe,” meaning “cabbage turnip.” To complement the flavor and texture of this crunchy vegetable, which reminds us of a cross between a white turnip and broccoli stems, we paired it with bright apple, tangy lime, and creamy sesame tahini.",
        price: 129,
    },
    {
        id: 24,
        image: "https://media.blueapron.com/recipes/93/c_main_dish_images/20140808-1743-162-3587/PorkTamales_Final_2_original.jpg?quality=80&width=850",
        category: "Pork",
        title: "Pork Tamales",
        subTitle: "with Smoked Chili Sauce and Mango",
        description: "It’s true that good things come in small packages, especially when it comes to tamales. The ancient Mayans, Aztecs, and Incas of Central and South America would agree, since they’ve been making these delicious bundles from as early as 7000 BC. The ancient warriors and hunters would pack tamales to go, the way we would a brown-bag lunch. Nowadays, you can’t miss the street vendors in Mexico supplying a steaming hot, portable snack to passersby.",
        price: 89,
    },
    {
        id: 25,
        image: "https://media.blueapron.com/recipes/1/square_newsletter_images/20150224-2305-30203-9164/FINALforCard-sq.jpg?quality=80&width=850",
        category: "Poultry",
        title: "Turkey Chili",
        subTitle: "with Avocado & Cheddar Cheese",
        description: "“Chili con carne,” typically shortened to just “chili,” is truly an American dish—more specifically, it’s attributed to San Antonio, Texas. Its history is long and colorful, marked by chili parlors, mom-and-pop chili shops, communal cook-offs and fiery controversy surrounding the inclusion of beans. (Here, we’re in favor!) Most importantly, though: chili is delicious. We’re making ours with turkey instead of beef and topping off the rich, delightfully spicy stew with cheddar cheese, avocado, cilantro and lime rounds.",
        price: 99,
    },
    {
        id: 26,
        image: "https://media.blueapron.com/recipes/3/c_main_dish_images/20140808-1608-36-4985/MainDishImage.jpg?quality=80&width=850",
        category: "Poultry",
        title: "Barbecue Cornish Game Hen",
        subTitle: "with Coleslaw & Sautéed Corn",
        description: "Barbecue chicken with slaw and corn is traditional across the American South. Flavors of the sauce itself can vary from state to state. Ours has a terrific balance of sweet and tangy notes and coats a Cornish game hen in place of chicken. We spice up the typical coleslaw and corn with sesame oil and cilantro. It’s a flavorful twist on an American classic!",
        price: 489,
    },
    {
        id: 27,
        image: "https://media.blueapron.com/recipes/7/square_newsletter_images/20150728-1515-139-6291/2P_072115_1_ThaiChickenBurgers_20-_209711SQ.jpg?quality=80&width=850",
        category: "Poultry",
        title: "Thai Chicken Burgers",
        subTitle: "with Hoisin Mayo & Roasted Potato Wedges",
        description: "In this dish, inspired by the cuisine of Thailand, we’re putting a uniquely delicious spin on chicken burgers. For incredible, authentic flavor, we’re sautéing aromatics—including citrusy lemongrass, an essential Thai ingredient—and mixing them into the patties. We’re also adding sesame oil, soy sauce and sriracha (a spicy, chile-based condiment) to complete the flavor profile. Slathered onto the toasted potato buns, a spread of hoisin sauce and mayonnaise adds creamy sweetness and richness. For a light, crispy side, we’re making homemade “fries” with long, hearty potato wedges, roasted in the oven.",
        price: 699,
    },
    {
        id: 28,
        image: "https://media.blueapron.com/recipes/10/c_main_dish_images/20140808-1612-78-7409/Final.jpg?quality=80&width=850",
        category: "Poultry",
        title: "Mexican-Style Chopped Salad",
        subTitle: "with Chicken & Corn",
        description: "Chopped salads have recently been added to the list of food crazes to sweep the nation in recent years. There’s a reason why they’re so popular—they feature small bites of lots of fresh, tasty ingredients! This one is a nod to Mexican cuisine where radishes and corn add crunch, and queso fresco, a mild, unaged cheese adds a touch of salty creaminess.",
        price: 789,
    },
    {
        id: 29,
        image: "https://media.blueapron.com/recipes/13/c_main_dish_images/20140808-1615-96-1390/ChickenThigh_Final_1_original.jpg?quality=80&width=850",
        category: "Poultry",
        title: "Chicken Thigh",
        subTitle: "with Dried Cherry and Pistachio Quinoa",
        description: "Most chicken enthusiasts believe that the dark meat is the most flavorful and moist part of the chicken. We agree, which is why we decided to feature the leg and thigh in this particular dish. Here, we paired the dark meat with dried cherries, pistachios and a tasty quinoa salad to pack a really flavorful punch. Finally, the plate is finished with a touch of French feta cheese to balance everything out. Enjoy!",
        price: 1199,
    },
    {
        id: 30,
        image: "https://media.blueapron.com/recipes/16/c_main_dish_images/20140808-1617-114-8031/chicken_20paillard_20baby_20potatoes_20tomatoes-1050.jpg?quality=80&width=850",
        category: "Poultry",
        title: "Chicken Paillard",
        subTitle: "with Warm Potato Salad",
        description: "Paillard is a French term that refers to meat that has been pounded thin and quickly cooked. This method of preparation not only tenderizes the meat but also cuts cooking time down dramatically! Marinated cherry tomatoes with fresh herbs and warm potato salad add touches of bright flavor to the simply seared chicken.",
        price: 1100,
    },
    {
        id: 31,
        image: "https://media.blueapron.com/recipes/4/c_main_dish_images/20140808-1608-42-0678/MainDishImage.jpg?quality=80&width=850",
        category: "Shellfish",
        title: "Lemongrass Shrimp",
        subTitle: "with Soba Noodles & Chinese Broccoli",
        description: "Lemongrass is an ancient herb from Southeast Asia used for a variety of purposes the world over. Interestingly, it repels most insects but attracts bees, and is known throughout the Philippines and Indonesia as a beekeeper’s friend. In this recipe, the bright citrusy notes of this exotic herb pair beautifully with shrimp and buckwheat soba noodles.",
        price: 369,
    },
    {
        id: 32,
        image: "https://media.blueapron.com/recipes/12/c_main_dish_images/20140808-1614-90-4694/MainDishImage.jpg?quality=80&width=850",
        category: "Shellfish",
        title: "Shrimp Spaghettini",
        subTitle: "with Chilis, Mint & Lemon",
        description: "Instead of traveling halfway across the world, we’re bringing the authentic flavors of Italy straight to you through this meal. A tribute to Italian coastal cuisine, which is marked by its simplicity and quality of ingredients, this dish of pasta and shrimp strikes the perfect balance with cool mint and hot red pepper flakes.",
        price: 897,
    },
    {
        id: 33,
        image: "https://media.blueapron.com/recipes/81/c_main_dish_images/20140808-1730-90-3744/ShrimpRisotto_BlueApron.jpg?quality=80&width=850",
        category: "Shellfish",
        title: "Shrimp Risotto",
        subTitle: "with Watercress",
        description: "Risotto is a type of rice dish that has a creamy, smooth consistency rather than the fluffy texture in other rice dishes. Arborio rice is the starchy, short-grained rice typically used for risotto. For best results, cook the grains until they are “al dente,” or until they are tender, but still have a slight bite.",
        price: 456,
    },
    {
        id: 34,
        image: "https://media.blueapron.com/recipes/127/square_newsletter_images/20151014-1908-18-3366/2P_100715_3_North_20AfricanPicedShrimpWithCouscous_20-_206757_20SQ.jpg?quality=80&width=850",
        category: "Shellfish",
        title: "North African-Spiced Shrimp & Couscous",
        subTitle: "with Dates, Kale & Carrots",
        description: "North Africa has a rich and diverse culinary tradition that deliciously blends European, Arabic and local influences. In this dish of spiced shrimp and lemony, aromatic couscous, we’re celebrating the region’s signature ingredients—from sweet, chewy dates to ras el hanout, a warming spice blend. And we’re pairing them with two seasonal vegetables, carrots and kale, for a satisfying and authentic dinner.",
        price: 479,
    },
    {
        id: 35,
        image: "https://media.blueapron.com/recipes/161/c_main_dish_images/20140808-1920-570-2230/FINAL_original.jpg?quality=80&width=850",
        category: "Shellfish",
        title: "Shrimp & Asparagus Fried Rice",
        subTitle: "Fried rice with salad",
        description: "Asparagus is one of the true symbols of spring. It even grows wild in backyards and forested areas throughout the country during this time. If the temperature is warm enough, the spears can grow up to 10 inches in a 24-hour period. For this recipe you’ll use a common green variety, but there are over 300 known varieties, including white and purple, that grow all around the world.",
        price: 549,
    },
    {
        id: 36,
        image: "https://media.blueapron.com/recipes/207/c_main_dish_images/20140808-2005-54-7141/FINAL_original.jpg?quality=80&width=850",
        category: "Shellfish",
        title: "Nettle Pasta",
        subTitle: "with Shrimp & Roasted Cauliflower",
        description: "A spring and summertime favorite in the Emilia-Romagna region of Italy, this long-cut green pasta made with stinging nettles is also called strettine. To remove their sting, the nettles must be boiled briefly before they’re pureed and incorporated into the pasta dough. With a flavor similar to spinach, nettle leaves are packed with a high concentration of beneficial nutrients like vitamins A, C, and K that hardy green vegetables are known for.",
        price: 578,
    },
    {
        id: 37,
        image: "https://media.blueapron.com/recipes/38/square_newsletter_images/20141218-2308-470-3459/38.jpg?quality=80&width=850",
        category: "Vegetarian",
        title: "Chickpea, Quinoa, and Vegetable Cakes",
        subTitle: "with Watercress Salad",
        description: "Chickpeas (also known as garbanzo beans, ceci beans, or channa) are a staple food used in Middle Eastern, Mediterranean and Indian cuisines. You can find them in soups, stews and hummus, ground to make bread, and even (in the late 1700’s) roasted and brewed as a coffee substitute. In this recipe you’ll combine them with hoisin sauce, Sriracha, sesame oil and silken tofu to create crispy, golden, lightly fried vegetable cakes.",
        price: 589,
    },
    {
        id: 38,
        image: "https://media.blueapron.com/recipes/39/c_main_dish_images/20140808-1641-54-6066/KabochaSquashRedCurry_BlueApron2.jpg?quality=80&width=850",
        category: "Vegetarian",
        title: "Kabocha Squash Red Curry",
        subTitle: "with Brown Rice",
        description: "The kabocha squash is a dark green, squat squash that resembles a pumpkin. Portuguese sailors introduced the kabocha squash to Japan in the mid-1500s, and it has been cultivated there ever since. It has a sweet, nutty flavor (think: a cross between a sweet potato and a pumpkin) and a fluffy texture.",
        price: 587,
    },
    {
        id: 39,
        image: "https://media.blueapron.com/recipes/40/square_newsletter_images/20141218-2309-5191-5617/40.jpg?quality=80&width=850",
        category: "Vegetarian",
        title: "Eggplant Lasagna",
        subTitle: "with Bechamel Sauce & Fresh Spinach Noodles",
        description: "This quick and easy lasagna will blow your mind. Traditional lasagna is a time-consuming process that can take hours. In this recipe you’ll use fresh spinach pasta and a creamy, smooth béchamel (one of the 5 French mother sauces) for a dish that preserves the deep, rich flavors of the classic but serves it in a fraction of the time. But what to do with the minutes you save? Enjoy!",
        price: 498,
    },
    {
        id: 40,
        image: "https://media.blueapron.com/recipes/52/c_main_dish_images/20140808-1701-120-9116/curriedgreenlentilspaneerbasmatirice_blueapron.jpg?quality=80&width=850",
        category: "Vegetarian",
        title: "Curried Green Lentils & Paneer",
        subTitle: "over Basmati Rice",
        description: "Paneer is a fresh, non-melting cheese commonly found in South Asian and Indian cuisine. It's made by adding lemon juice or vinegar to heated milk to separate the curds and the whey. Then, the curds are drained and excess liquid is pressed from the cheese. Finally, the cheese is wrapped in cloth and pressed under a heavy weight before packing or cooking.",
        price: 575,
    },
    {
        id: 41,
        image: "https://media.blueapron.com/recipes/53/c_main_dish_images/20140808-1702-126-5036/UdonTempehSoup_BlueApron.jpg?quality=80&width=850",
        category: "Vegetarian",
        title: "Udon Noodle Soup",
        subTitle: "with Chinese Broccoli & Seared Tempeh",
        description: "Tempeh is a high-protein soy product that originated in Indonesia in the early 1800s. It is made by soaking soybeans and partially cooking them, then fermenting them for a day or two, resulting in a unique texture and earthy flavor. Tempeh is also a great source of essential minerals, like calcium and manganese.",
        price: 698,
    },
    {
        id: 42,
        image: "https://media.blueapron.com/recipes/54/square_newsletter_images/20150604-1948-497-7992/FINALforCard.jpg?quality=80&width=850",
        category: "Vegetarian",
        title: "Black Bean & Red Quinoa Enchiladas",
        subTitle: "with Salsa Verde",
        description: "Enchiladas, from the Spanish word for “seasoned with chile,” once consisted simply of tortillas dipped in chile sauce and eaten as a snack on the streets of Mexico. Today, though, the dish has evolved into much more. In our version, the chile is a poblano (a mild variety popular in the Mexican state of Puebla)—and we’re using it, along with seasonal tomatillos, to create a salsa verde. We’re rolling the tortillas around a filling of spiced black beans and red quinoa and baking them for a hearty, flavorful summer entree.",
        price: 587,
    },
    {
        id: 43,
        image: "https://media.blueapron.com/recipes/1290/square_newsletter_images/20150708-1619-348-9629/2P_062615_1_Lamb_20Meatballs_20with_20Garlic_20Toasts_20__20Summer_20Squash_20Salad_20-_208003.jpg?quality=80&width=850",
        category: "african",
        title: "Spiced Meatballs",
        subTitle: "with Garlic Toasts & Summer Squash Salad",
        description: "Spiced meatballs served in a warming tomato sauce are a North African specialty. And one of their defining features is a hint of lemon. The bright citrus cuts the richness of the meatballs, perfectly balancing the dish. Here, we’re including dried lemon peel in a blend of spices used to flavor the meatballs. And we’re adding lemon zest and juice to a refreshing summer squash, mint and olive salad—served right on top of the meatballs, to bring the dish’s flavors together. And to complete the meal, we’re making crunchy, garlic baguette toasts, perfect for dipping in the sauce.",
        price: 27,
    },
    {
        id: 44,
        image: "https://media.blueapron.com/recipes/1391/square_newsletter_images/20151008-1916-99-9840/2P_092915_4_RasElHanout-SpicedCod_20-_206290_20SQ.jpg?quality=80&width=850",
        category: "african",
        title: "Crispy Cod & Spiced Couscous",
        subTitle: "with Acorn Squash & Rainbow Chard",
        description: "Spice blends are an easy way to achieve rich, complex depth of flavor. In this recipe, we’re using ras el hanout, a traditional Moroccan blend that features a delicious mosaic of warming Middle Eastern spices. We’re infusing couscous and sprinkling sweet and nutty acorn squash with the ras el hanout, and serving both with chickpea flour-crusted cod, rainbow chard and sweet golden raisins. Garnished with mint, this meal redefines cold-weather comfort food with each layered, aromatic bite.",
        price: 768,
    },
    {
        id: 45,
        image: "https://media.blueapron.com/recipes/304/square_newsletter_images/20141218-2127-2-7740/lamb-sausage-SQ.png?quality=80&width=850",
        category: "african",
        title: "Lamb & Butternut Squash Soup",
        subTitle: "with Spinach & Barley",
        description: "Merguez sausage is a staple of North African, Middle Eastern and European cuisines. It’s usually made with lamb and a blend of spices, bringing a hearty, warming flavor to the dishes it’s used in. Normally, you’ll find it wrapped up in sausage casing. But in this recipe, instead of using pre-made merguez sausages, you’ll create your own by mixing the lamb with our custom spice blend—no casing required. Cooking the meat without a casing allows the flavors to infuse the butternut squash and barley. The soup’s on, chefs!",
        price: 78,
    },
    {
        id: 46,
        image: "https://media.blueapron.com/recipes/2086/square_newsletter_images/1484258947-4-2727/1-23_202PP_20West_20African_20Peanut_20Chicken_20-12789_v2_SQ.jpg?quality=80&width=850",
        category: "african",
        title: "West African Peanut Chicken",
        subTitle: "with Sautéed Kale & Rice",
        description: "This recipe celebrates the flavors of mafé, a hearty peanut stew that hails from Senegal. Instead of stewing our chicken, we’re basting it in a peanut sauce—which gets its sweet, aromatic, piquant character from a traditional mix of spices, including paprika, coriander and two kinds of peppercorn. On the side, vinegar-infused rice acts as a tart counterpoint to the sauce’s rich peanut butter and coconut milk.",
        price: 457,
    },
    {
        id: 47,
        image: "https://media.blueapron.com/recipes/286/c_main_dish_images/20140808-2022-186-0980/IMG_8436.jpg?quality=80&width=850",
        category: "african",
        title: "Shakshouka",
        subTitle: "with Lemony Bibb Lettuce Salad",
        description: "The word shakshouka means “a mixture” in Arabic slang. Throughout North Africa and the Middle East, this dish of eggs poached in a spiced tomato sauce is just as popular for breakfast as it is for dinner. To round out the meal, we added fingerling potatoes to the mixture, and a crisp, bright salad of Bibb lettuce with a lemon and Dijon vinaigrette on the side.",
        price: 836,
    },
    {
        id: 48,
        image: "https://media.blueapron.com/recipes/2/c_main_dish_images/20140808-1607-30-3725/Main_20Dish_20Image.jpg?quality=80&width=850",
        category: "american",
        title: "Seared Hanger Steak",
        subTitle: "with Rosemary Fingerling Potatoes & Green Bean Salad",
        description: "Prized for its flavor, hanger steak is the choice cut of beef for those in the know. It has even earned the nickname butcher's steak because butchers would often reserve it for themselves rather than offering it for sale. In this dish, we highlight the hanger steak's incredible flavor by serving it alongside jewel-like potatoes and a crisp green bean salad.",
        price: 255,
    },
    {
        id: 49,
        image: "https://media.blueapron.com/recipes/17/c_main_dish_images/20140808-1618-120-9907/FishTacos_BlueApron.jpg?quality=80&width=850",
        category: "american",
        title: "Chili-Dusted Fish Tacos",
        subTitle: "with Pickled Red Cabbage, Mango & Avocado",
        description: "This Mexican-inspired meal is a symphony of bright flavors and contrasting textures. The fresh cilantro and lime bring out the creaminess of the avocado, while the pickled cabbage and the spicy radish add snap and crunch. All of these sensations complement the flaky and tender tilapia fish. The final product—a colorful dish fit for a fiesta that we hope you’ll enjoy.",
        price: 786,
    },
    {
        id: 50,
        image: "https://media.blueapron.com/recipes/447/square_newsletter_images/20141218-2130-2-9407/Lamb_20Sliders-2536.jpg?quality=80&width=850",
        category: "american",
        title: "Lamb & Beef Sliders",
        subTitle: "with Harissa-Labneh Sauce & Cucumber Salad",
        description: "This spin on an American classic uses a rich blend of lamb and beef to create six flavorful mini burgers. You’ll season the patties with aromatics, lemon zest and a mix of traditional Middle Eastern spices. Slathered with labneh cheese (a creamy variety made from yogurt) and harissa (a signature North African spice paste), we’re bringing big flavors to these small burgers.",
        price: 425,
    },
    {
        id: 51,
        image: "https://media.blueapron.com/recipes/11/c_main_dish_images/20140808-1613-84-3678/MainDishImage.jpg?quality=80&width=850",
        category: "american",
        title: "Pork Chops",
        subTitle: "with Smashed Sweet Potato, Roasted Broccoli & Herbs",
        description: "As summer winds down, farmers start to harvest beautiful broccoli and a wide array of amazing potatoes. In this dish, we feature classic, juicy, center-cut pork chops with roasted broccoli and smashed sweet potato. Maple sugar, the reduced solid of maple syrup, not only helps us look forward to fall, but also lends a touch of sweetness to this dish.",
        price: 978,
    },
    {
        id: 52,
        image: "https://media.blueapron.com/recipes/3/c_main_dish_images/20140808-1608-36-4985/MainDishImage.jpg?quality=80&width=850",
        category: "american",
        title: "Barbecue Cornish Game Hen",
        subTitle: "with Coleslaw & Sautéed Corn",
        description: "Barbecue chicken with slaw and corn is traditional across the American South. Flavors of the sauce itself can vary from state to state. Ours has a terrific balance of sweet and tangy notes and coats a Cornish game hen in place of chicken. We spice up the typical coleslaw and corn with sesame oil and cilantro. It’s a flavorful twist on an American classic!",
        price: 525,
    },
    {
        id: 53,
        image: "https://media.blueapron.com/recipes/422/square_newsletter_images/20141218-2128-2-0570/Scallops_20w-_20Sun_20Gold_20Tomatoes_20__20Farro-7884.jpg?quality=80&width=850",
        category: "american",
        title: "Pan-Seared Scallops",
        subTitle: "with Sautéed Sun Gold Tomatoes & Purslane over Farro",
        description: "We’re pulling out all the stops. For the second time in Blue Apron history, we have the privilege of offering you scallops. Scallops roam seas the world over. Their bright shells with fluted, fanned ridges are unmistakable−as is their flavor. Delicate and subtly briny, we’ve chosen to prepare the scallop simply. Finished with purslane, an almost lemony herb with a peppery kick, this gourmet dish is pure elegance.",
        price: 578,
    },
    {
        id: 54,
        image: "https://media.blueapron.com/recipes/38/square_newsletter_images/20141218-2308-470-3459/38.jpg?quality=80&width=850",
        category: "american",
        title: "Chickpea, Quinoa, and Vegetable Cakes",
        subTitle: "with Watercress Salad",
        description: "Chickpeas (also known as garbanzo beans, ceci beans, or channa) are a staple food used in Middle Eastern, Mediterranean and Indian cuisines. You can find them in soups, stews and hummus, ground to make bread, and even (in the late 1700’s) roasted and brewed as a coffee substitute. In this recipe you’ll combine them with hoisin sauce, Sriracha, sesame oil and silken tofu to create crispy, golden, lightly fried vegetable cakes.",
        price: 254,
    },
    {
        id: 55,
        image: "https://media.blueapron.com/recipes/9/c_main_dish_images/20140808-1611-72-7880/GingerBeefStir_20Fry_BlueApron.jpg?quality=80&width=850",
        category: "asian",
        title: "Ginger Beef Stir-Fry",
        subTitle: "with Tatsoi & Jasmine Rice",
        description: "Hoisin sauce is a key flavor component in sauces and glazes in many Asian-inspired dishes. Made from soybean paste, garlic, chilis, and various spices, this all-in-one ingredient is salty, sweet, and spiced at the same time. In this super-fast recipe, we mix half of the hoisin into the stir-fry and spoon the rest over the finished product for an elegant finish.",
        price: 757,
    },
    {
        id: 56,
        image: "https://media.blueapron.com/recipes/42/square_newsletter_images/20141218-2319-47-2185/42.jpg?quality=80&width=850",
        category: "asian",
        title: "Pan-Seared Cod",
        subTitle: "with Soy Maple Glaze, Baby Bok Choy, and Rice Noodles",
        description: "Baby bok choy is a cruciferous vegetable, like broccoli and kale, that thrives in the colder months. Our Vermont maple syrup is also harvested in the colder months. In late March, sugar maples start transforming the starch the’ve stored all winter into a sweet sap that’s harvested directly from the trunk. The harvested liquid is boiled down to 1/40th of its original volume to make the concentrated, delicious maple syrup in this recipe.",
        price: 786,
    },
    {
        id: 57,
        image: "https://media.blueapron.com/recipes/255/c_main_dish_images/20140808-2016-138-7011/IMG_6359.jpg?quality=80&width=850",
        category: "asian",
        title: "Lamb & Beef Rice Noodles",
        subTitle: "with Mint, Lime & Ponzu",
        description: "This dish is inspired by the cuisines of Southeast Asia where the focus is on the balance of sour, salty, sweet, and bitter flavors. Here, sour comes from both the lime juice and the ponzu, a Japanese citrus sauce. Soy sauce adds saltiness and coconut palm sugar adds sweetness to help achieve that balance. Regular salt and pepper are still key for rounding out flavors, so don’t forget to season and taste as you go.",
        price: 244,
    },
    {
        id: 58,
        image: "https://media.blueapron.com/recipes/247/c_main_dish_images/20140808-2013-72-7297/IMG_7237_original.jpg?quality=80&width=850",
        category: "asian",
        title: "Five-Spice Pork Chops",
        subTitle: "with Plum Sauce, Chinese Broccoli & Purple Sweet Potato",
        description: "This purple sweet potato, also known as Okinawan sweet potato, isn’t even a member of the potato family—it’s part of the same family as morning glory, or water spinach. The plant is native to the Americas and landed in Japan sometime in the 1500s. It grew so well there that it became popular in many Japanese dishes and now can be found throughout Asia and the Pacific.",
        price: 485,
    },
    {
        id: 60,
        image: "https://media.blueapron.com/recipes/28/c_main_dish_images/20140808-1630-186-8035/ChickenWings_Final_original.jpg?quality=80&width=850",
        category: "asian",
        title: "Roasted Chicken Wings",
        subTitle: "with Chinese Long Beans & Sweet Potato",
        description: "Long beans, also known as yardlong beans or snake beans, are very similar to the familiar green beans, but can be up to 30 inches long. They grow very quickly in a warm climate and need to be harvested nearly every day. These beans are tender, crisp, and the perfect side to the slightly sweet and spicy wings. Enjoy!",
        price: 277,
    },
    {
        id: 61,
        image: "https://media.blueapron.com/recipes/4/c_main_dish_images/20140808-1608-42-0678/MainDishImage.jpg?quality=80&width=850",
        category: "asian",
        title: "Lemongrass Shrimp",
        subTitle: "",
        description: "",
        price: 287,
    },
    {
        id: 62,
        image: "https://media.blueapron.com/recipes/219/square_newsletter_images/20141218-2126-2-7105/soba-noodles-SQ.jpg?quality=80&width=850",
        category: "asian",
        title: "Chilled Sesame Soba Noodle Salad",
        subTitle: "with Spiced Cashews",
        description: "Stay cool with this chilly summer noodle dish. Soba noodles are made with buckwheat flour (“soba” is the Japanese word for buckwheat). They’re traditionally served either hot in a soup, or cold with a dipping sauce. This time of year, we like the cold preparation, served up with fresh pea shoots, crunchy cucumbers and candied, spiced cashews.",
        price: 277,
    },
    {
        id: 63,
        image: "https://media.blueapron.com/recipes/2133/square_newsletter_images/1486678488-4-0003-9207/220-2PM-Lamb-Beef-Mushroom-Stew-20835_x1b_WEB_Center.jpg?quality=80&width=850",
        category: "british",
        title: "Lamb, Beef & Mushroom Stew",
        subTitle: "with Parmesan Potatoes & Chives",
        description: "This dish is inspired by the rich, complex flavor of shepherd’s pie, a hearty meat stew topped with a mashed potato crust. We’re cooking ground lamb and beef with vegetables like mushrooms and celery, plus zesty, aromatic spices like garlic powder, fennel seed and savory. And instead of mashed potatoes, we're topping our finished stew with thin slices of roasted potato, topped with a bit of nutty parmesan cheese.",
        price: 2189,
    },
    {
        id: 64,
        image: "https://media.blueapron.com/recipes/3329/square_newsletter_images/1540327692-365-0002-2905/1029_FPF_Fish_Chips_0011_WEB_SQ.jpg?quality=80&width=850",
        category: "british",
        title: "Crispy Fish Fillets & Potato Wedges",
        subTitle: "with Homemade Tartar Sauce & Roasted Brussels Sprouts",
        description: "In this sophisticated spin on classic fish and chips, our pollock is coated with flavorful spices and delicate potato flakes, then cooked to crispy perfection. We’re serving it alongside potatoes (roasted with the same blend of spices) and an irresistible tartar sauce, for dipping.",
        price: 781,
    },
    {
        id: 65,
        image: "https://media.blueapron.com/recipes/1551/square_newsletter_images/20160218-1539-4-2977/FP_021016_4_SpringShepherdsPie_20-_201300_SQ.jpg?quality=80&width=850",
        category: "british",
        title: "Spring Shepherd's Pie",
        subTitle: "with Cremini Mushrooms & English Peas",
        description: "By the 18th Century, the potato, native to the Americas, began appearing in a range of European comfort dishes. One delicious example is shepherd’s pie, a British classic that combines a hearty meat and vegetable filling with a creamy mashed potato crust. Our seasonal shepherd’s pie features lamb and beef cooked with fresh English peas, cremini mushrooms and traditional spices—all baked under a layer of mashed Yukon Golds. It’s a warming, wholesome way to welcome some of spring’s first produce.",
        price: 889,
    },
    {
        id: 66,
        image: "https://media.blueapron.com/recipes/1574/square_newsletter_images/20160311-1726-4-5507/2P_030216_2_SpicedPorkChops-5625_SQ.jpg?quality=80&width=850",
        category: "british",
        title: "Spiced Pork Chops & Mashed Potatoes",
        subTitle: "with Kale, English Peas & Goat Cheese",
        description: "Hearty pork and potatoes, a favorite pairing in British cuisine, make for incredibly satisfying comfort food. In this recipe, we’re serving pan-seared pork chops—coated with the warm flavors of fennel, coriander and more—over a bed of mashed potatoes and tender kale. Fresh peas, brightened up with shallot, complete this delicious, simple meal with a springtime flourish.",
        price: 741,
    },
    {
        id: 67,
        image: "https://media.blueapron.com/recipes/2815/square_newsletter_images/1519409914-1-0061-2611/0305_FPM_Pork_2535_WEB_SQ.jpg?quality=80&width=850",
        category: "british",
        title: "Sheet Pan Roasted Pork & Sweet Potatoes",
        subTitle: "with Creamy Kale",
        description: "For hands-off cooking, we’re roasting spice-rubbed pork and sweet potato wedges on the same sheet pan in this recipe. Sautéed kale coated with creamy goat cheese makes for a sophisticated side.",
        price: 237,
    },
    {
        id: 68,
        image: "https://media.blueapron.com/recipes/180/square_newsletter_images/20141218-2231-5243-3492/180.jpg?quality=80&width=850",
        category: "british",
        title: "Mushroom & Sweet Potato Shepherd’s Pie",
        subTitle: "with Fresh Green Garbanzo Beans",
        description: "There’s a world of difference between fresh and canned (or dried) garbanzo beans. For this delicious update of a classic, we’re providing garbanzos fresh from the vine, still in their pods. Lightly sautéing the beans brings out their mild flavor and preserves their delightful crunch. Combined with mushrooms, herbs and aromatics, these beans provide a tasty base for this hearty, sweet potato crust.",
        price: 788,
    },
    {
        id: 69,
        image: "https://media.blueapron.com/recipes/27781/square_newsletter_images/1622203315-28-0031-7605/0628_2P12_Cajun-Steak_9351_sq_Web.jpg?quality=80&width=850",
        category: "cajun creole",
        title: "Grilled Cajun Flank Steaks & Potato Salad",
        subTitle: "with Butter Lettuce & Crispy Onion Salad",
        description: "Grilled steaks (topped with a spicy compound butter) are perfectly complemented by a classic summer side of creamy potato salad—made with foil packet fingerlings, grilled onion, mayo, and sweet pickle relish.",
        price: 698,
    },
    {
        id: 70,
        image: "https://media.blueapron.com/recipes/200/c_main_dish_images/20140808-2005-684-2528/FINAL_original.jpg?quality=80&width=850",
        category: "cajun creole",
        title: "Bronzed Salmon with Orange Marmalade",
        subTitle: "& Israeli Couscous",
        description: "Myra’s Bronzed Salmon with Orange Marmalade and Israeli Couscous is the proud winner of our Mother’s Day Recipe Contest! The recipe, submitted by Myra’s daughter Lyla, hits all the right sweet, sour, and spicy notes. Myra pats the salmon with a mix of Cajun spices and brown sugar, then sears the salmon in a skillet, caramelizing the sugar and giving the salmon its “bronzed” character.",
        price: 356,
    },
    {
        id: 71,
        image: "https://media.blueapron.com/recipes/31344/square_newsletter_images/1644343314-28-0015-9417/0314_FPF_Salmon-Asparagus_281_SQ_Web.jpg?quality=80&width=850",
        category: "cajun creole",
        title: "Sheet Pan Cajun-Spiced Salmon",
        subTitle: "with Roasted Potatoes, Asparagus & Garlic-Chive Dressing",
        description: "Chefs! We’re bringing you a series of recipes designed with ease of cooking and cleanup in mind, but without sacrificing the incredible flavors you’ve come to expect from a classic Blue Apron meal. The star of this dish is the bright, creamy dressing we’re serving alongside our salmon, featuring a rich mix of sour cream, buttermilk, hot sauce, chives, and more––served with a roasted vegetable duo.",
        price: 783,
    },
    {
        id: 72,
        image: "https://media.blueapron.com/recipes/88/square_newsletter_images/20141218-2124-2-1798/Chicken_20Gumbo-0602.jpg?quality=80&width=850",
        category: "cajun creole",
        title: "Chicken Gumbo",
        subTitle: "with Sausage and Okra",
        description: "Gumbo is a time-honored stew from Southern Louisiana. It borrows from several culinary traditions−notably Native American, West African and French. To create the base of this dish, you’ll use the “trinity” of aromatics popular in Cajun cuisine: onion, celery and bell pepper. To build the gumbo’s hearty texture, you’ll add okra, another hallmark of Southern cooking. Traditionally, the dish is made for social gatherings and shared. With that in mind, we’re delighted to share it with you.",
        price: 497,
    },
    {
        id: 73,
        image: "https://media.blueapron.com/recipes/1805/square_newsletter_images/1470425741-4-8157/090516_2PF_SouthernStyleShrimp-0091_SQ.jpg?quality=80&width=850",
        category: "cajun creole",
        title: "Paprika Shrimp & Cheddar Grits",
        subTitle: "with Tomato & Sweet Corn",
        description: "This recipe celebrates a coastal Southern favorite: shrimp and grits. We’re finishing our shrimp, seasoned with smoky-sweet paprika, in a fresh tomato, lemon and butter sauce. And we’re cooking our grits (simply dried and ground corn) with juicy kernels straight off the cob—before melting sharp cheddar into the pot. (For just the right consistency, be sure to whisk your grits every so often, transforming them into a deliciously smooth porridge.)",
        price: 277,
    },
    {
        id: 74,
        image: "https://media.blueapron.com/recipes/281/c_main_dish_images/20140808-2021-114-0045/FINAL.jpg?quality=80&width=850",
        category: "cajun creole",
        title: "Heirloom Potato-Pepper Hash",
        subTitle: "with Remoulade Sauce",
        description: "Hash can really be any combination of chopped vegetables or potatoes. The word hash actually derives from the French word “hacher,” or to chop. Halved fingerling potatoes and chopped pepper and onion that are browned in a hot pan make up this one. For a bright and fresh addition, we finished off the warm vegetables with fresh Brussels sprout leaves, frisee, and some creamy remoulade sauce.",
        price: 435,
    }
]
localStorage.setItem("api", JSON.stringify(mainApi));
toogleLogin();
function toogleLogin() {
    let loginChecker = JSON.parse(localStorage.getItem("userInfo")) || null;
    if (loginChecker == null) {
        document.querySelector(".regestration").style.display = "block";
        document.querySelector(".welcome-container").style.display = "none";
    } else {
        document.querySelector(".regestration").style.display = "none";
        document.querySelector(".welcome-container").style.display = "block";
    }
}
document.getElementById("logout").addEventListener("click", () => {
    localStorage.removeItem("userInfo");
    localStorage.removeItem("cartInfo");
    toogleLogin();
    location.href = "./index.html"
})

// hamburger 
const menu = document.querySelector(".menu");
const menuItems = document.querySelectorAll(".menuItem");
const hamburger= document.querySelector(".hamburger");
const closeIcon= document.querySelector(".closeIcon");
const menuIcon = document.querySelector(".menuIcon");


function toggleMenu() {
  if (menu.classList.contains("showMenu")) {
    menu.classList.remove("showMenu");
    closeIcon.style.display = "none";
    menuIcon.style.display = "block";
  } else {
    menu.classList.add("showMenu");
    closeIcon.style.display = "block";
    menuIcon.style.display = "none";
  }
}

hamburger.addEventListener("click", toggleMenu);
menuItems.forEach( 
    function(menuItem) { 
      menuItem.addEventListener("click", toggleMenu);
    }
  )