const mainApi = [
    {
        id: 1,
        image: "https://media.blueapron.com/recipes/2/c_main_dish_images/20140808-1607-30-3725/Main_20Dish_20Image.jpg?quality=80&width=850",
        category: "beaf",
        title: "Seared Hanger Steak",
        subTitle: "with Rosemary Fingerling Potatoes & Green Bean Salad",
        description: "Prized for its flavor, hanger steak is the choice cut of beef for those in the know. It has even earned the nickname 'butcher's steak' because butchers would often reserve it for themselves rather than offering it for sale. In this dish, we highlight the hanger steak's incredible flavor by serving it alongside jewel-like potatoes and a crisp green bean salad.",
    },
    {
        id: 2,
        image: "https://media.blueapron.com/recipes/5/c_main_dish_images/20140808-1609-48-5109/MainDishImage.jpg?quality=80&width=850",
        category: "beaf",
        title: "Fresh Fettucelle Bolognese",
        subTitle: "with Baby Heirloom Carrots",
        description: "This comforting meal pays homage to the succulent pasta dishes of Bologna in northern Italy. The Bolognese meat sauce slowly simmers with Italian tomatoes and fresh heirloom carrots for an extra touch of sweetness. Just before serving, the dish is topped with aromatic basil, the quintessential finishing touch for any Italian masterpiece.",
    },
    {
        id: 3,
        image: "https://media.blueapron.com/recipes/9/c_main_dish_images/20140808-1611-72-7880/GingerBeefStir_20Fry_BlueApron.jpg?quality=80&width=850",
        category: "beaf",
        title: "Ginger Beef Stir-Fry",
        subTitle: "with Tatsoi & Jasmine Rice",
        description: "Hoisin sauce is a key flavor component in sauces and glazes in many Asian-inspired dishes. Made from soybean paste, garlic, chilis, and various spices, this all-in-one ingredient is salty, sweet, and spiced at the same time. In this super-fast recipe, we mix half of the hoisin into the stir-fry and spoon the rest over the finished product for an elegant finish.",
    },
    {
        id: ,
        image: "",
        category: "",
        title: "",
        subTitle: "",
        description: "",
    },
    {
        id: ,
        image: "",
        category: "",
        title: "",
        subTitle: "",
        description: "",
    },
    {
        id: ,
        image: "",
        category: "",
        title: "",
        subTitle: "",
        description: "",
    },
    {
        id: ,
        image: "",
        category: "",
        title: "",
        subTitle: "",
        description: "",
    },
    {
        id: ,
        image: "",
        category: "",
        title: "",
        subTitle: "",
        description: "",
    },
    {
        id: ,
        image: "",
        category: "",
        title: "",
        subTitle: "",
        description: "",
    },
    {
        id: ,
        image: "",
        category: "",
        title: "",
        subTitle: "",
        description: "",
    },
    {
        id: ,
        image: "",
        category: "",
        title: "",
        subTitle: "",
        description: "",
    },
    {
        id: ,
        image: "",
        category: "",
        title: "",
        subTitle: "",
        description: "",
    },
    {
        id: ,
        image: "",
        category: "",
        title: "",
        subTitle: "",
        description: "",
    },
    {
        id: ,
        image: "",
        category: "",
        title: "",
        subTitle: "",
        description: "",
    },
    {
        id: ,
        image: "",
        category: "",
        title: "",
        subTitle: "",
        description: "",
    },
    {
        id: ,
        image: "",
        category: "",
        title: "",
        subTitle: "",
        description: "",
    },
    {
        id: ,
        image: "",
        category: "",
        title: "",
        subTitle: "",
        description: "",
    },
    {
        id: ,
        image: "",
        category: "",
        title: "",
        subTitle: "",
        description: "",
    },
    {
        id: ,
        image: "",
        category: "",
        title: "",
        subTitle: "",
        description: "",
    },
    {
        id: ,
        image: "",
        category: "",
        title: "",
        subTitle: "",
        description: "",
    },
    {
        id: ,
        image: "",
        category: "",
        title: "",
        subTitle: "",
        description: "",
    },
    {
        id: ,
        image: "",
        category: "",
        title: "",
        subTitle: "",
        description: "",
    },
    {
        id: ,
        image: "",
        category: "",
        title: "",
        subTitle: "",
        description: "",
    },
    {
        id: ,
        image: "",
        category: "",
        title: "",
        subTitle: "",
        description: "",
    },
    {
        id: ,
        image: "",
        category: "",
        title: "",
        subTitle: "",
        description: "",
    },
    {
        id: ,
        image: "",
        category: "",
        title: "",
        subTitle: "",
        description: "",
    },
    {
        id: ,
        image: "",
        category: "",
        title: "",
        subTitle: "",
        description: "",
    },
    {
        id: ,
        image: "",
        category: "",
        title: "",
        subTitle: "",
        description: "",
    },
    {
        id: ,
        image: "",
        category: "",
        title: "",
        subTitle: "",
        description: "",
    },
    {
        id: ,
        image: "",
        category: "",
        title: "",
        subTitle: "",
        description: "",
    },
    {
        id: ,
        image: "",
        category: "",
        title: "",
        subTitle: "",
        description: "",
    },
    {
        id: ,
        image: "",
        category: "",
        title: "",
        subTitle: "",
        description: "",
    },
    {
        id: ,
        image: "",
        category: "",
        title: "",
        subTitle: "",
        description: "",
    },
    {
        id: ,
        image: "",
        category: "",
        title: "",
        subTitle: "",
        description: "",
    },
    {
        id: ,
        image: "",
        category: "",
        title: "",
        subTitle: "",
        description: "",
    },
    {
        id: ,
        image: "",
        category: "",
        title: "",
        subTitle: "",
        description: "",
    },
    {
        id: ,
        image: "",
        category: "",
        title: "",
        subTitle: "",
        description: "",
    },
    {
        id: ,
        image: "",
        category: "",
        title: "",
        subTitle: "",
        description: "",
    },
    {
        id: ,
        image: "",
        category: "",
        title: "",
        subTitle: "",
        description: "",
    },
    {
        id: ,
        image: "",
        category: "",
        title: "",
        subTitle: "",
        description: "",
    },
    {
        id: ,
        image: "",
        category: "",
        title: "",
        subTitle: "",
        description: "",
    },
    {
        id: ,
        image: "",
        category: "",
        title: "",
        subTitle: "",
        description: "",
    },
    {
        id: ,
        image: "",
        category: "",
        title: "",
        subTitle: "",
        description: "",
    },
    {
        id: ,
        image: "",
        category: "",
        title: "",
        subTitle: "",
        description: "",
    },
    {
        id: ,
        image: "",
        category: "",
        title: "",
        subTitle: "",
        description: "",
    },
    {
        id: ,
        image: "",
        category: "",
        title: "",
        subTitle: "",
        description: "",
    },
    {
        id: ,
        image: "",
        category: "",
        title: "",
        subTitle: "",
        description: "",
    },
    {
        id: ,
        image: "",
        category: "",
        title: "",
        subTitle: "",
        description: "",
    },
    {
        id: ,
        image: "",
        category: "",
        title: "",
        subTitle: "",
        description: "",
    },
    {
        id: ,
        image: "",
        category: "",
        title: "",
        subTitle: "",
        description: "",
    }
]